# Generated by Django 3.0 on 2022-05-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='create_time',
        ),
    ]
